---
version: '3.7'
services:
  ## MySQL Docker Compose Config
  mysql-iasf:
    container_name: mysql-iasf
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: iasf-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3309:3306"
    restart: always